#!/usr/bin/env bash

################################
# Shows info about sound/volume.
#
# Dependencies:
# - ponymix
# - font awesome (icons)
#
################################

vol=$(ponymix get-volume)
$(ponymix is-muted) # Return an exit code of 0 if muted, otherwise 1

# Set the mute status and the color
if [ $(echo $?) = 0 ]; then
    is_muted=true
    color="#DC322F"
else
    is_muted=false
    color="#93A1A1"
fi

# Determine icon
if [ $vol -eq 0 ] || $is_muted; then
        icon=""
else
    if [ $vol -le 33 ]; then
        icon=""
    else
        icon=""
    fi
fi

echo $icon $vol"%" # full text
echo $icon $vol"%" # short text
echo $color
exit 0 # status
