alias g='git'
alias ga='git add'
alias gbra='git branch'
alias gchp='git cherry-pick'
alias gcko='git checkout'
alias gckob='git checkout -b'
alias gcom='git commit'
alias gcoma='git commit --amend'
alias gdi='git diff'
alias gdis='git diff --staged'
# Output: abbreviated_commit_hash (%h, in green) | commit_message (%s) | author_name (%an, in yellow) | commit_date_relative (%cr)
alias glo='git log --pretty=format:"%C(green)%h%C(reset) %C(bold)|%C(reset) %s %C(bold)|%C(reset) %C(yellow)%an%C(reset) %C(bold)|%C(reset) %cr"'
# Outputs git aliases, without comments
alias gls='cat ~/dotfiles/zsh/.config/zsh/aliases/git.zsh | ag -v '^\#' | cut --characters=7-'
alias gpu='git push'
alias gpuf='git push --force-with-lease'
alias gpure='git pull --rebase --autostash'
alias greb='git rebase'
alias grebc='git rebase --continue'
alias grebi='git rebase -i'
alias gres='git reset'
alias gsh='git show'
alias gsta='git status'
