alias g='git'
alias ga='git add'
alias gbra='git branch'
alias gchp='git cherry-pick'
alias gcko='git checkout'
alias gckob='git checkout -b'
alias gcom='git commit'
alias gcoma='git commit --amend'
alias gdi='git diff'
alias gdis='git diff --staged'
# Output: abbreviated_commit_hash (%h) | commit_message (%s) | author_name (%an, in yellow) | commit_date_relative (%cr, in green)
alias glo='git log --pretty=format:"%h %C(bold)|%C(reset) %s %C(bold)|%C(reset) %C(yellow)%an%C(reset) %C(bold)|%C(reset) %C(green)%cr%C(reset)"'
# Copy a string from the output of the glo alias (a commit hash for example)
alias gloy='glo | yank'
# Outputs git aliases, without comments
alias gls='cat ~/dotfiles/zsh/.config/zsh/aliases/git.zsh | ag --invert-match '^\#' | cut --characters=7-'
alias gpu='git push'
alias gpuf='git push --force-with-lease'
alias gpure='git pull --rebase --autostash'
alias greb='git rebase'
alias grebc='git rebase --continue'
alias grebi='git rebase --interactive'
alias gres='git reset'
alias gsh='git show'
alias gsta='git status'
