# Prompt when removing more than 3 files at a time and do not remove '/'
alias rm='rm --interactive=once --preserve-root'
# Fail to operate recursively on '/'
alias chown='chown --preserve-root'
alias chmod='chmod --preserve-root'
alias chgrp='chgrp --preserve-root'
